name: Hacker | EddieRangel.com
markdown: redcarpet
pygments: true
include: [js, bootstrap.min.js, site.js]
include: [font, glyphicons-halflings-regular.eot, glyphicons-halflings-regular.svg, glyphicons-halflings-regular.ttf, glyphicons-halflings-regular.woff]
#include: [archives, index.html]
#destination: ../erangeljr.github.io
#LOCAL DEVELOPMENT
url:         http://localhost:4000
#PRODUCTION
#url:         http://eddierangel.com

# Github repositories
github_user: erangeljr
github_repo_url: https://github.com/erangeljr/erangeljr.github.io

# Disqus Comments
disqus_short_name: eddierangelcom
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-47781516-1

# Twitter
twitter_user: eddie_31003
twitter_tweet_button: true
